macros:
    - theorem_short
    - algebra
    - analysis
    - asgn_enumitem
    - tikz

formatting: header
contents: solutions

substitutions:
    doctype: article
    lmargin: 2cm
    rmargin: 3cm
    tmargin: 3cm
    bmargin: 4cm
