macros:
    - theorem_short
    - algebra
    - analysis
formatting: header
contents: enumerate

substitutions:
    doctype: article
    lmargin: 2cm
    rmargin: 3cm
    tmargin: 3cm
    bmargin: 4cm
