macros:
    - theorem
    - algebra
    - analysis
    - tikz

formatting: titlepage
contents: chapter

substitutions:
    doctype: memoir
    lmargin: 2.5cm
    rmargin: 2.5cm
    tmargin: 2.5cm
    bmargin: 2.5cm
