macros:
    - theorem
    - algebra
    - analysis
    - tikz

formatting: titlepage
contents: chapter

substitutions:
    doctype: memoir
    lmargin: 3cm
    rmargin: 3cm
    tmargin: 3cm
    bmargin: 4cm
